### ISSUE TITLE
Setweak command not updating grades in list

### ISSUE THREAD

**Issue by willowisp01** [AY2324S2-CS2103T-T09-1/tp#110]
The people are not tagged as weak if the command is entered more than once. To replicate the issue:
- Reset the addressbook
- Set the threshold to B.
- Now set the threshold to A+. Everyone should be weak, but the weak tags are not updated.

**Comment by ronnnnnnnnn** [comment]
I believe the issue is in line 32 of SetWeakThresholdCommand:
```
model.updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);
```
The list update only happens once, possibly because in the subsequent times the predicate being set is still the same so the list doesn't actually update. If the list is manually updated (e.g. through the find command), the change in weak threshold will be reflected.

**Comment by yashma-sonara** [comment]
Done in latest pr.
